#!/usr/bin/env python3
"""
Database merger and JS module generator.

Combines per-vendor JSON outputs into a single unified database,
then generates the ES module (.js) that the React app imports directly.

Usage:
    python merge_and_generate.py --vendor-dir ../output/vendor/ --output ../output/
"""

from __future__ import annotations
import argparse
import json
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any


def merge_vendor_databases(vendor_dir: str) -> dict[str, Any]:
    """
    Merge all vendor JSON files from a directory into one unified database.
    """
    vendor_path = Path(vendor_dir)
    all_materials: dict[str, Any] = {}
    vendor_stats: dict[str, dict[str, int]] = {}

    json_files = sorted(vendor_path.glob("*.json"))
    if not json_files:
        print(f"  No vendor JSON files found in {vendor_dir}")
        return {"schema_version": "1.0.0", "materials": {}}

    for fp in json_files:
        print(f"  Loading {fp.name}...")
        db = json.loads(fp.read_text(encoding="utf-8"))
        vendor_name = db.get("vendor", fp.stem)
        materials = db.get("materials", {})

        count_by_status = {"seed": 0, "partial": 0, "complete": 0, "verified": 0}

        for mat_id, record in materials.items():
            if mat_id in all_materials:
                # Conflict resolution: keep the one with more data
                existing_curves = len([
                    c for c in all_materials[mat_id].get("curves", {}).values()
                    if c.get("samples") and len(c["samples"]) > 0
                ])
                new_curves = len([
                    c for c in record.get("curves", {}).values()
                    if c.get("samples") and len(c["samples"]) > 0
                ])
                if new_curves <= existing_curves:
                    print(f"    Skipping duplicate {mat_id} (existing has more data)")
                    continue
                else:
                    print(f"    Replacing {mat_id} with version from {vendor_name}")

            all_materials[mat_id] = record
            status = record.get("record_status", "seed")
            count_by_status[status] = count_by_status.get(status, 0) + 1

        vendor_stats[vendor_name] = count_by_status
        print(f"    {len(materials)} materials from {vendor_name}")

    merged = {
        "schema_version": "1.0.0",
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "vendor_stats": vendor_stats,
        "materials": all_materials,
    }

    return merged


def generate_js_module(db: dict[str, Any], output_path: str) -> None:
    """
    Generate the ES module that the React app imports.

    This creates a .js file with:
    - The full material database as an exported const
    - Helper functions for lookup, filtering, and interpolation
    """
    materials = db.get("materials", {})

    # Compact the JSON for the JS file (no indent for samples arrays)
    db_json = json.dumps(db, separators=(",", ":"))

    js_content = textwrap.dedent(f'''\
    // ═══════════════════════════════════════════════════════════════════════
    // Material Database for EMI Filter Design App
    // Auto-generated by material_pipeline on {db.get("generated_utc", "unknown")}
    // {len(materials)} materials across {len(db.get("vendor_stats", {}))} vendor(s)
    // ═══════════════════════════════════════════════════════════════════════
    // DO NOT EDIT — regenerate with: python merge_and_generate.py

    export const MATERIAL_DB = {db_json};

    // ── Lookup helpers ──────────────────────────────────────────────────

    /**
     * Get a material record by its full ID (e.g. "FR_43", "TDK_N30").
     * @param {{string}} id - Material ID
     * @returns {{object|null}} Material record or null
     */
    export function getMaterial(id) {{
      return MATERIAL_DB.materials[id] || null;
    }}

    /**
     * List all materials, optionally filtered.
     * @param {{object}} [filter] - Filter criteria
     * @param {{string}} [filter.vendor] - Vendor name
     * @param {{string}} [filter.family] - Material family
     * @param {{string}} [filter.tag] - Required application tag
     * @param {{string}} [filter.minStatus] - Minimum record status
     * @param {{string}} [filter.chemistry] - Chemistry type (MnZn, NiZn, etc.)
     * @returns {{object[]}} Array of matching material records
     */
    export function listMaterials(filter = {{}}) {{
      const statusOrder = ["seed", "partial", "complete", "verified"];
      return Object.values(MATERIAL_DB.materials).filter(m => {{
        if (filter.vendor && m.vendor !== filter.vendor) return false;
        if (filter.family && m.family !== filter.family) return false;
        if (filter.chemistry && m.chemistry !== filter.chemistry) return false;
        if (filter.tag && !(m.application_tags || []).includes(filter.tag)) return false;
        if (filter.minStatus) {{
          if (statusOrder.indexOf(m.record_status) < statusOrder.indexOf(filter.minStatus))
            return false;
        }}
        return true;
      }});
    }}

    /**
     * Get unique values for a field across all materials (for building filter dropdowns).
     * @param {{string}} field - "vendor", "family", "chemistry", or "record_status"
     * @returns {{string[]}} Sorted unique values
     */
    export function getFilterOptions(field) {{
      const vals = new Set();
      Object.values(MATERIAL_DB.materials).forEach(m => {{
        if (field === "vendor" || field === "family" || field === "chemistry" || field === "record_status") {{
          if (m[field]) vals.add(m[field]);
        }}
      }});
      return [...vals].sort();
    }}

    // ── Interpolation ───────────────────────────────────────────────────

    /**
     * Interpolate a curve at a given x value.
     * Uses log-space interpolation for frequency axes (standard for magnetics data).
     *
     * @param {{string}} materialId - Material ID
     * @param {{string}} curveName - Curve key (e.g. "complex_perm_vs_f")
     * @param {{number}} xTarget - Target x value
     * @returns {{number[]|null}} Interpolated y values, or null if unavailable
     */
    export function interpolateCurve(materialId, curveName, xTarget) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat) return null;
      const curve = (mat.curves || {{}})[curveName];
      if (!curve || !curve.samples || curve.samples.length < 2) return null;

      const samples = curve.samples;
      const useLog = ["frequency"].includes(curve.x_quantity);

      const xArr = samples.map(s => useLog ? Math.log10(Math.max(s[0], 1e-30)) : s[0]);
      const xT = useLog ? Math.log10(Math.max(xTarget, 1e-30)) : xTarget;

      // Clamp to range
      if (xT <= xArr[0]) return samples[0].slice(1);
      if (xT >= xArr[xArr.length - 1]) return samples[samples.length - 1].slice(1);

      // Binary search
      let lo = 0, hi = xArr.length - 1;
      while (hi - lo > 1) {{
        const mid = (lo + hi) >> 1;
        if (xArr[mid] <= xT) lo = mid; else hi = mid;
      }}

      const t = (xT - xArr[lo]) / (xArr[hi] - xArr[lo]);
      return samples[lo].slice(1).map((v, i) => v + t * (samples[hi][i + 1] - v));
    }}

    /**
     * Get complex permeability (µ' and µ'') at a given frequency.
     * @param {{string}} materialId - Material ID
     * @param {{number}} fHz - Frequency in Hz
     * @returns {{{{muPrime: number, muDoublePrime: number}}|null}}
     */
    export function getComplexPermeability(materialId, fHz) {{
      const vals = interpolateCurve(materialId, "complex_perm_vs_f", fHz);
      if (!vals || vals.length < 2) return null;
      return {{ muPrime: vals[0], muDoublePrime: vals[1] }};
    }}

    /**
     * Compute choke impedance from complex permeability.
     * Z = jωL + R_core, where L ∝ µ' and R_core ∝ ωµ''
     *
     * @param {{string}} materialId - Material ID
     * @param {{number}} fHz - Frequency in Hz
     * @param {{number}} N - Number of turns
     * @param {{number}} Ae_m2 - Effective cross-section area in m²
     * @param {{number}} le_m - Effective magnetic path length in m
     * @returns {{{{Z_mag: number, Z_phase_deg: number, L_H: number, R_core: number}}|null}}
     */
    export function getChokeImpedance(materialId, fHz, N, Ae_m2, le_m) {{
      const mu = getComplexPermeability(materialId, fHz);
      if (!mu) return null;

      const mu0 = 4 * Math.PI * 1e-7;
      const omega = 2 * Math.PI * fHz;
      const AL = mu0 * Ae_m2 / le_m; // AL per turn² (without µ)

      const L = mu.muPrime * AL * N * N;
      const R_core = omega * mu.muDoublePrime * AL * N * N;

      const XL = omega * L;
      const Z_mag = Math.sqrt(R_core * R_core + XL * XL);
      const Z_phase_deg = Math.atan2(XL, R_core) * 180 / Math.PI;

      return {{ Z_mag, Z_phase_deg, L_H: L, R_core }};
    }}

    /**
     * Get all available curve names for a material.
     * @param {{string}} materialId - Material ID
     * @returns {{string[]}} Curve names
     */
    export function getAvailableCurves(materialId) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat || !mat.curves) return [];
      return Object.keys(mat.curves).filter(k => {{
        const c = mat.curves[k];
        return c.samples && c.samples.length > 0;
      }});
    }}

    /**
     * Get curve metadata (units, test conditions) without the samples.
     * Useful for building chart axes and legends.
     * @param {{string}} materialId - Material ID
     * @param {{string}} curveName - Curve key
     * @returns {{object|null}} Curve metadata (no samples array)
     */
    export function getCurveMetadata(materialId, curveName) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat) return null;
      const curve = (mat.curves || {{}})[curveName];
      if (!curve) return null;
      const {{ samples, ...meta }} = curve;
      meta.sampleCount = (samples || []).length;
      return meta;
    }}

    // ── Core loss & Steinmetz ───────────────────────────────────────

    /**
     * Compute core loss from fitted Steinmetz parameters: Pv = k * f^alpha * B^beta.
     * @param {{string}} materialId - Material ID
     * @param {{number}} f_Hz - Frequency in Hz
     * @param {{number}} B_mT - Peak flux density in mT
     * @returns {{number|null}} Power loss in kW/m^3, or null if no fit available
     */
    export function getSteinmetzLoss(materialId, f_Hz, B_mT) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat) return null;
      const s = (mat.fitted_models || {{}}).steinmetz;
      if (!s) return null;
      return s.k * Math.pow(f_Hz, s.alpha) * Math.pow(B_mT, s.beta);
    }}

    /**
     * Interpolate core loss from digitized curves at a given frequency and flux density.
     * Finds the two nearest frequency curves and interpolates in log-log space.
     * @param {{string}} materialId - Material ID
     * @param {{number}} f_Hz - Frequency in Hz
     * @param {{number}} B_mT - Peak flux density in mT
     * @returns {{number|null}} Power loss in kW/m^3, or null if unavailable
     */
    export function getCoreLoss(materialId, f_Hz, B_mT) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat || !mat.curves) return null;

      // Collect core loss curves with their frequencies
      const freqCurves = [];
      for (const [key, curve] of Object.entries(mat.curves)) {{
        if (!key.startsWith("core_loss_vs_B_") || !curve.samples || curve.samples.length < 2) continue;
        const suffix = key.replace("core_loss_vs_B_", "").toLowerCase();
        let freq = parseFreqSuffix(suffix);
        if (freq > 0) freqCurves.push({{ freq, samples: curve.samples }});
      }}
      if (freqCurves.length === 0) return null;
      freqCurves.sort((a, b) => a.freq - b.freq);

      // Interpolate P_v at B_mT for a single frequency curve (log-log)
      function pvAtB(samples, B) {{
        const logB = Math.log10(Math.max(B, 1e-30));
        const xs = samples.map(s => Math.log10(Math.max(s[0], 1e-30)));
        const ys = samples.map(s => Math.log10(Math.max(s[1], 1e-30)));
        if (logB <= xs[0]) return Math.pow(10, ys[0]);
        if (logB >= xs[xs.length - 1]) return Math.pow(10, ys[ys.length - 1]);
        let lo = 0, hi = xs.length - 1;
        while (hi - lo > 1) {{ const mid = (lo + hi) >> 1; if (xs[mid] <= logB) lo = mid; else hi = mid; }}
        const t = (logB - xs[lo]) / (xs[hi] - xs[lo]);
        return Math.pow(10, ys[lo] + t * (ys[hi] - ys[lo]));
      }}

      // Single frequency — just interpolate in B
      if (freqCurves.length === 1) return pvAtB(freqCurves[0].samples, B_mT);

      // Find bracketing frequencies
      const logF = Math.log10(f_Hz);
      const logFs = freqCurves.map(c => Math.log10(c.freq));
      if (logF <= logFs[0]) return pvAtB(freqCurves[0].samples, B_mT);
      if (logF >= logFs[logFs.length - 1]) return pvAtB(freqCurves[freqCurves.length - 1].samples, B_mT);

      let lo = 0;
      for (let i = 0; i < logFs.length - 1; i++) {{ if (logFs[i] <= logF) lo = i; }}
      const hi = lo + 1;
      const t = (logF - logFs[lo]) / (logFs[hi] - logFs[lo]);

      // Interpolate between two frequency curves in log(P_v) space
      const pv_lo = pvAtB(freqCurves[lo].samples, B_mT);
      const pv_hi = pvAtB(freqCurves[hi].samples, B_mT);
      return Math.pow(10, Math.log10(pv_lo) + t * (Math.log10(pv_hi) - Math.log10(pv_lo)));
    }}

    function parseFreqSuffix(s) {{
      const m = s.match(/^([\\d.]+)(hz|khz|mhz|ghz)$/);
      if (!m) return 0;
      const mult = {{hz:1, khz:1e3, mhz:1e6, ghz:1e9}}[m[2]];
      return parseFloat(m[1]) * mult;
    }}

    // ── Temperature-dependent properties ────────────────────────────

    /**
     * Interpolate permeability at a given temperature from perm_vs_temp curve.
     * @param {{string}} materialId - Material ID
     * @param {{number}} T_C - Temperature in degrees C
     * @returns {{number|null}} Permeability, or null if unavailable
     */
    export function getPermVsTemp(materialId, T_C) {{
      return interpolateCurve(materialId, "perm_vs_temp", T_C)?.[0] ?? null;
    }}

    /**
     * Interpolate saturation flux density at a given temperature.
     * @param {{string}} materialId - Material ID
     * @param {{number}} T_C - Temperature in degrees C
     * @returns {{number|null}} Flux density in gauss, or null if unavailable
     */
    export function getFluxVsTemp(materialId, T_C) {{
      return interpolateCurve(materialId, "flux_vs_temp", T_C)?.[0] ?? null;
    }}

    // ── B-H curves ──────────────────────────────────────────────────

    /**
     * Get B-H curve samples for a material at the nearest available temperature.
     * @param {{string}} materialId - Material ID
     * @param {{number}} [temp_C=25] - Desired temperature in C
     * @returns {{{{samples: number[][], temp_C: number}}|null}} B-H data or null
     */
    export function getBHCurve(materialId, temp_C = 25) {{
      const mat = MATERIAL_DB.materials[materialId];
      if (!mat || !mat.curves) return null;

      // Find bh_curve keys and pick nearest temperature
      let best = null, bestDiff = Infinity;
      for (const [key, curve] of Object.entries(mat.curves)) {{
        if (!key.startsWith("bh_curve") || !curve.samples || curve.samples.length < 2) continue;
        const tc = (curve.test_conditions || {{}}).temperature_C;
        const t = typeof tc === "number" ? tc : 25;
        const diff = Math.abs(t - temp_C);
        if (diff < bestDiff) {{ bestDiff = diff; best = {{ samples: curve.samples, temp_C: t }}; }}
      }}
      return best;
    }}
    ''')

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    Path(output_path).write_text(js_content, encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Merge vendor databases and generate JS module")
    parser.add_argument("--vendor-dir", default="output/vendor/",
                        help="Directory containing per-vendor JSON files")
    parser.add_argument("--output", default="output/",
                        help="Output directory for merged DB and JS module")
    args = parser.parse_args()

    print("Material database merger + JS generator")
    print("=" * 50)

    # Step 1: Merge vendor databases
    print("\nMerging vendor databases...")
    merged = merge_vendor_databases(args.vendor_dir)

    materials = merged.get("materials", {})
    status_counts = {}
    for m in materials.values():
        s = m.get("record_status", "unknown")
        status_counts[s] = status_counts.get(s, 0) + 1

    print(f"\n  Total: {len(materials)} materials")
    for status, count in sorted(status_counts.items()):
        print(f"    {status}: {count}")

    # Step 2: Write merged JSON
    json_path = Path(args.output) / "material_db.json"
    json_path.parent.mkdir(parents=True, exist_ok=True)
    json_path.write_text(json.dumps(merged, indent=2), encoding="utf-8")
    json_size = json_path.stat().st_size
    print(f"\n  Wrote {json_path} ({json_size / 1024:.1f} KB)")

    # Step 3: Generate JS module
    js_path = Path(args.output) / "material_db.js"
    generate_js_module(merged, str(js_path))
    js_size = js_path.stat().st_size
    print(f"  Wrote {js_path} ({js_size / 1024:.1f} KB)")

    # Step 4: Summary
    print(f"\n{'=' * 50}")
    print("  Database ready for React app import:")
    print(f"    import {{ getMaterial, getComplexPermeability }} from './material_db.js';")


if __name__ == "__main__":
    main()
