<script setup>
import Header from '../components/Header.vue'
import Footer from '../components/Footer.vue'
</script>

<template>
   <div class="d-flex flex-column min-vh-100">

       <Header />
       <div class="container text-white" style="">
                <br><br>
                <br><br>
            <p>If you are reading this, you are a braver man/woman than me. This is the typical stuff that only lawyers and other soulless creatures care about. If you are really worried about what this webpage does with your data, let me tell you: we don't store personal data further than whatever we need to identify you in the and when the login section is enabled. Any technical data that you introduce here will be anonymized, randomized, and added to a public database for the use of AI training of magnetics in the future. Yes, we will use part of your knowledge to train an AI, but it will be public, along the training data. If you don't like this, which is understandable, this is an open-source project, you are free to get a copy and install in your premises, and your data will not be used for public knowledge improvement. If you don't know how to do that, feel free to contact us at openmagnetics@protonmail.com and we can do it for you.</p>
          <span>
            <h2 style="font-weight: normal;">Preamble</h2>
            <p>With the following privacy policy we would like to inform you which types of your personal data (hereinafter also abbreviated as "data") we process for which purposes and in which scope. The privacy statement applies to all processing of personal data carried out by us, both in the context of providing our services and in particular on our websites, in mobile applications and within external online presences, such as our social media profiles (hereinafter collectively referred to as "online services"). The terms used are not gender-specific.<br>Last Update: 21 October 2024<br><br>Table of contents</p>
             <ul style="font-size: 15px;" type="disc">
                <li>Preamble<br><br></li>
                <li>Controller<br><br></li>
                <li>Overview of processing operations<br><br></li>
                <li>Legal Bases for the Processing<br><br></li>
                <li>Security Precautions<br><br></li>
                <li>Transmission and Disclosure of Personal Data<br><br></li>
                <li>Data Processing in Third Countries<br><br></li>
                <li>Use of Cookies<br><br></li>
                <li>Provision of online services and web hosting<br><br></li>
                <li>Contacting us<br><br></li>
                <li>Web Analysis, Monitoring and Optimization<br><br></li>
                <li>Onlinemarketing<br><br></li>
                <li>Profiles in Social Networks (Social Media)<br><br></li>
                <li>Erasure of data<br><br></li>
                <li>Changes and Updates to the Privacy Policy<br><br></li>
                <li>Rights of Data Subjects<br><br></li>
                <li>Terminology and Definitions</li>
             </ul>
             <p>E-mail address:&nbsp;<a href="mailto:openmagnetics@protonmail.com">openmagnetics@protonmail.com</a></p>
             <p><strong>Overview of processing operations</strong></p>
             <p>The following table summarises the types of data processed, the purposes for which they are processed and the concerned data subjects.</p>
             <p><strong>Categories of Processed Data</strong></p>
             <ul style="font-size: 15px;" type="disc">
                <li>Inventory data (e.g. names, addresses).<br><br></li>
                <li>Content data (e.g. text input, photographs, videos).<br><br></li>
                <li>Contact data (e.g. e-mail, telephone numbers).<br><br></li>
                <li>Meta/communication data (e.g. device information, IP addresses).<br><br></li>
                <li>Usage data (e.g. websites visited, interest in content, access times).<br><br></li>
                <li>Location data (Data that indicates the location of the end device of an end user).</li>
             </ul>
             <p><strong>Categories of Data Subjects</strong></p>
             <ul style="font-size: 15px;" type="disc">
                <li>Prospective customers.<br><br></li>
                <li>Communication partner (Recipients of e-mails, letters, etc.).<br><br></li>
                <li>Users (e.g. website visitors, users of online services).</li>
             </ul>
             <p><strong>Purposes of Processing</strong></p>
             <ul style="line-height: 1.15; font-size: 15px;" type="disc">
                <li>A/B Tests.<br><br></li>
                <li>Conversion Tracking.<br><br></li>
                <li>Clicktracking.<br><br></li>
                <li>Cross-Device Tracking (Device-independent processing of user data for marketing purposes).<br><br></li>
                <li>Feedback (e.g. collecting feedback via online form).<br><br></li>
                <li>Heatmaps ("Heatmaps" are mouse movements of the users, which are combined to an overall picture.).<br><br></li>
                <li>Interest-based and behavioral marketing.<br><br></li>
                <li>contact requests and communication.<br><br></li>
                <li>Conversion tracking (Measurement of the effectiveness of marketing activities).<br><br></li>
                <li>Profiling (Creating user profiles).<br><br></li>
                <li>Remarketing.<br><br></li>
                <li>Web Analytics (e.g. access statistics, recognition of returning visitors).<br><br></li>
                <li>Targeting (e.g. profiling based on interests and behaviour, use of cookies).<br><br></li>
                <li>Polls and Questionnaires (e.g. surveys with input options, multiple choice questions).<br><br></li>
                <li>Custom Audiences (Selection of relevant target groups for marketing purposes or other output of content).<br><br></li>
               <li><strong>Consent (Article 6 (1) (a) GDPR)</strong><span>&nbsp;</span>- The data subject has given consent to the processing of his or her personal data for one or more specific purposes.<br><br></li>
               <li><strong>Performance of a contract and prior requests (Article 6 (1) (b) GDPR)</strong><span>&nbsp;</span>- Performance of a contract to which the data subject is party or in order to take steps at the request of the data subject prior to entering into a contract.<br><br></li>
               <li><strong>Legitimate Interests (Article 6 (1) (f) GDPR)</strong><span>&nbsp;</span>- Processing is necessary for the purposes of the legitimate interests pursued by the controller or by a third party, except where such interests are overridden by the interests or fundamental rights and freedoms of the data subject which require protection of personal data.</li>
             </ul>
             <p><strong>Web Analysis, Monitoring and Optimization</strong></p>
            <p>Web analysis is used to evaluate the visitor traffic on our website and may include the behaviour, interests or demographic information of users, such as age or gender, as pseudonymous values. With the help of web analysis we can e.g. recognize, at which time our online services or their functions or contents are most frequently used or requested for repeatedly, as well as which areas require optimization.</p>
             <p>In addition to web analysis, we can also use test procedures, e.g. to test and optimize different versions of our online services or their components.</p>
            <p>For these purposes, so-called user profiles can be created and stored in a file (so-called "cookie") or similar procedures in which the relevant user information for the aforementioned analyses is stored. This information may include, for example, content viewed, web pages visited and elements and technical data used there, such as the browser used, computer system used and information on times of use. If users have consented to the collection of their location data, these may also be processed, depending on the provider.</p>
            <p>The IP addresses of the users are also stored. However, we use any existing IP masking procedure (i.e. pseudonymisation by shortening the IP address) to protect the user. In general, within the framework of web analysis, A/B testing and optimisation, no user data (such as e-mail addresses or names) is stored, but pseudonyms. This means that we, as well as the providers of the software used, do not know the actual identity of the users, but only the information stored in their profiles for the purposes of the respective processes.</p>
            <p><strong>Information on legal basis:</strong><span>&nbsp;</span>If we ask the users for their consent to the use of third party providers, the legal basis of the processing is consent. Furthermore, the processing can be a component of our (pre)contractual services, provided that the use of the third party was agreed within this context. Otherwise, user data will be processed on the basis of our legitimate interests (i.e. interest in efficient, economic and recipient friendly services). In this context, we would also like to refer you to the information on the use of cookies in this privacy policy.</p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Processed data types:</strong><span>&nbsp;</span>Usage data (e.g. websites visited, interest in content, access times), Meta/communication data (e.g. device information, IP addresses).<br><br></li>
                <li><strong>Data subjects:</strong><span>&nbsp;</span>Users (e.g. website visitors, users of online services).<br><br></li>
               <li><strong>Purposes of Processing:</strong><span>&nbsp;</span>Web Analytics (e.g. access statistics, recognition of returning visitors), Targeting (e.g. profiling based on interests and behaviour, use of cookies), Conversion Tracking, Profiling (Creating user profiles), Clicktracking, A/B Tests, Feedback (e.g. collecting feedback via online form), Heatmaps ("Heatmaps" are mouse movements of the users, which are combined to an overall picture.), Polls and Questionnaires (e.g. surveys with input options, multiple choice questions).<br><br></li>
                <li><strong>Security measures:</strong><span>&nbsp;</span>IP Masking (Pseudonymization of the IP address).<br><br></li>
                <li><strong>Legal Basis:</strong><span>&nbsp;</span>Consent (Article 6 (1) (a) GDPR), Legitimate Interests (Article 6 (1) (f) GDPR).</li>
             </ul>
             <p style="font-size: 15px;"><strong>Services and service providers being used:</strong></p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Hotjar:</strong><span>&nbsp;</span>Testing and Optimization; Service provider: Hotjar Ltd., 3 Lyons Range, 20 Bisazza Street, Sliema SLM 1640, Malta ;<br>Website:<span>&nbsp;</span><a href="https://www.hotjar.com/" target="_blank" rel="noopener">https://www.hotjar.com</a>; <br>Security measures: &nbsp;IP Masking (Pseudonymization of the IP address); <br>Privacy Policy: <a href="https://www.hotjar.com/legal/policies/privacy" target="_blank" rel="noopener">https://www.hotjar.com/legal/policies/privacy</a>.<br>Cookie Policy:<span>&nbsp;</span><a href="https://www.hotjar.com/legal/policies/cookie-information" target="_blank" rel="noopener">https://www.hotjar.com/legal/policies/cookie-information</a>; <br>Retention period: The cookies that Hotjar uses have a different "lifetime"; some last up to 365 days, some only last during the current visit; <br>Opt-Out:<span>&nbsp;</span><a href="https://www.hotjar.com/legal/compliance/opt-out" target="_blank" rel="noopener">https://www.hotjar.com/legal/compliance/opt-out</a>.</li>
             </ul>
             <p><strong>Onlinemarketing</strong></p>
            <p>We process personal data for the purposes of online marketing, which may include in particular the marketing of advertising space or the display of advertising and other content (collectively referred to as "Content") based on the potential interests of users and the measurement of their effectiveness.</p>
            <p>For these purposes, so-called user profiles are created and stored in a file (so-called "cookie") or similar procedure in which the relevant user information for the display of the aforementioned content is stored. This information may include, for example, content viewed, websites visited, online networks used, communication partners and technical information such as the browser used, computer system used and information on usage times. If users have consented to the collection of their sideline data, these can also be processed.</p>
            <p>The IP addresses of the users are also stored. However, we use provided IP masking procedures (i.e. pseudonymisation by shortening the IP address) to ensure the protection of the user's by using a pseudonym. In general, within the framework of the online marketing process, no clear user data (such as e-mail addresses or names) is secured, but pseudonyms. This means that we, as well as the providers of online marketing procedures, do not know the actual identity of the users, but only the information stored in their profiles.</p>
            <p>The information in the profiles is usually stored in the cookies or similar memorizing procedures. These cookies can later, generally also on other websites that use the same online marketing technology, be read and analyzed for purposes of content display, as well as supplemented with other data and stored on the server of the online marketing technology provider.</p>
            <p>Exceptionally, clear data can be assigned to the profiles. This is the case, for example, if the users are members of a social network whose online marketing technology we use and the network links the profiles of the users in the aforementioned data. Please note that users may enter into additional agreements with the social network providers or other service providers, e.g. by consenting as part of a registration process.</p>
            <p>As a matter of principle, we only gain access to summarised information about the performance of our advertisements. However, within the framework of so-called conversion measurement, we can check which of our online marketing processes have led to a so-called conversion, i.e. to the conclusion of a contract with us. The conversion measurement is used alone for the performance analysis of our marketing activities.</p>
             <p>Unless otherwise stated, we kindly ask you to consider that cookies used will be stored for a period of two years.</p>
            <p><strong>Information on legal basis:</strong><span>&nbsp;</span>If we ask users for their consent (e.g. in the context of a so-called "cookie banner consent"), the legal basis for processing data for online marketing purposes is this consent. Otherwise, user data will be processed on the basis of our legitimate interests (i.e. interest in the analysis, optimisation and economic operation of our online services. In this context, we would also like to refer you to the information on the use of cookies in this privacy policy.</p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Processed data types:</strong><span>&nbsp;</span>Usage data (e.g. websites visited, interest in content, access times), Meta/communication data (e.g. device information, IP addresses), Location data (Data that indicates the location of the end device of an end user).<br><br></li>
                <li><strong>Data subjects:</strong><span>&nbsp;</span>Users (e.g. website visitors, users of online services), Prospective customers.<br><br></li>
               <li><strong>Purposes of Processing:</strong><span>&nbsp;</span>Targeting (e.g. profiling based on interests and behaviour, use of cookies), Remarketing, Conversion Tracking, Interest-based and behavioral marketing, Profiling (Creating user profiles), Conversion tracking (Measurement of the effectiveness of marketing activities), Web Analytics (e.g. access statistics, recognition of returning visitors), Custom Audiences (Selection of relevant target groups for marketing purposes or other output of content), Cross-Device Tracking (Device-independent processing of user data for marketing purposes).<br><br></li>
                <li><strong>Security measures:</strong><span>&nbsp;</span>IP Masking (Pseudonymization of the IP address).<br><br></li>
                <li><strong>Legal Basis:</strong><span>&nbsp;</span>Consent (Article 6 (1) (a) GDPR), Legitimate Interests (Article 6 (1) (f) GDPR).<br><br></li>
               <li><strong>Opt-Out:</strong><span>&nbsp;</span>We refer to the privacy policies of the respective service providers and the possibilities for objection (so-called "opt-out"). If no explicit opt-out option has been specified, it is possible to deactivate cookies in the settings of your browser. However, this may restrict the functions of our online offer. We therefore recommend the following additional opt-out options, which are offered collectively for each area:<br>a) Europe:<span>&nbsp;</span><a href="https://www.youronlinechoices.eu/" target="_blank" rel="noopener">https://www.youronlinechoices.eu</a>. <br>b) Canada:<span>&nbsp;</span><a href="https://www.youradchoices.ca/choices" target="_blank" rel="noopener">https://www.youradchoices.ca/choices</a>. <br>c) USA:<span>&nbsp;</span><a href="https://www.aboutads.info/choices" target="_blank" rel="noopener">https://www.aboutads.info/choices</a>. <br>d) Cross-regional:<span>&nbsp;</span><a href="https://optout.aboutads.info/" target="_blank" rel="noopener">https://optout.aboutads.info</a>.</li>
             </ul>
             <p><strong>Services and service providers being used:</strong></p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Google Tag Manager:</strong><span>&nbsp;</span>Google Tag Manager is a solution with which we can manage so-called website tags via an interface and thus integrate other services into our online services. The Tag Manager itself (which implements the tags) does not process any personal user data. With regard to the processing of users' personal data, reference is made to the information below regarding Google services. Service provider: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland, parent company: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; Website:<span>&nbsp;</span><a href="https://marketingplatform.google.com/" target="_blank" rel="noopener">https://marketingplatform.google.com</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://policies.google.com/privacy" target="_blank" rel="noopener">https://policies.google.com/privacy</a>.<br><br></li>
               <li><strong>Google Analytics:</strong><span>&nbsp;</span>Online marketing and web analytics; Service provider: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland, parent company: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; Website:<span>&nbsp;</span><a href="https://marketingplatform.google.com/intl/en/about/analytics/" target="_blank" rel="noopener">https://marketingplatform.google.com/intl/en/about/analytics/</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://policies.google.com/privacy" target="_blank" rel="noopener">https://policies.google.com/privacy</a>; <br>Opt-Out: Opt-Out Plugin:<span>&nbsp;</span><a href="https://tools.google.com/dlpage/gaoptout?hl=en" target="_blank" rel="noopener">https://tools.google.com/dlpage/gaoptout?hl=en</a>, <br>Settings for the Display of Advertisements:<span>&nbsp;</span><a href="https://adssettings.google.com/authenticated" target="_blank" rel="noopener">https://adssettings.google.com/authenticated</a>.<br><br></li>
               <li><strong>Google Ads and Conversion Tracking:</strong><span>&nbsp;</span>We use the Google "Ads" online marketing method to place ads on the Google advertising network (e.g., in search results, videos, websites, etc.) so that they are displayed to users who have an alleged interest in the ads. We also measure the conversion of the ads. However, we only know the anonymous total number of users who clicked on our ad and were redirected to a page tagged with a conversion tracking tag. However, we ourselves do not receive any information that can be used to identify users. Service provider: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland, parent company: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA;<br>Website:&nbsp;<a href="https://marketingplatform.google.com/" target="_blank" rel="noopener">https://marketingplatform.google.com</a>; <br>Privacy Policy:&nbsp;<a href="https://policies.google.com/privacy" target="_blank" rel="noopener">https://policies.google.com/privacy</a>.<br><br></li>
               <li><strong>Facebook Pixel:</strong><span>&nbsp;</span>Service provider:<span>&nbsp;</span><a href="https://www.facebook.com/" target="_blank" rel="noopener">https://www.facebook.com</a>, Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Ireland, parent company: Facebook, 1 Hacker Way, Menlo Park, CA 94025, USA; Website:<span>&nbsp;</span><a href="https://www.facebook.com/" target="_blank" rel="noopener">https://www.facebook.com</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://www.facebook.com/about/privacy" target="_blank" rel="noopener">https://www.facebook.com/about/privacy</a>; <br>Opt-Out:<span>&nbsp;</span><a href="https://www.facebook.com/settings?tab=ads" target="_blank" rel="noopener">https://www.facebook.com/settings?tab=ads</a>.</li>
             </ul>
             <p><strong>Profiles in Social Networks (Social Media)</strong></p>
            <p>We maintain online presences within social networks and process user data in this context in order to communicate with the users active there or to offer information about us.</p>
            <p>We would like to point out that user data may be processed outside the European Union. This may entail risks for users, e.g. by making it more difficult to enforce users' rights.</p>
            <p>In addition, user data is usually processed within social networks for market research and advertising purposes. For example, user profiles can be created on the basis of user behaviour and the associated interests of users. The user profiles can then be used, for example, to place advertisements within and outside the networks which are presumed to correspond to the interests of the users. For these purposes, cookies are usually stored on the user's computer, in which the user's usage behaviour and interests are stored. Furthermore, data can be stored in the user profiles independently of the devices used by the users (especially if the users are members of the respective networs or will become members later on).</p>
            <p>For a detailed description of the respective processing operations and the opt-out options, please refer to the respective data protection declarations and information provided by the providers of the respective networks.</p>
            <p>Also in the case of requests for information and the exercise of rights of data subjects, we point out that these can be most effectively pursued with the providers. Only the providers have access to the data of the users and can directly take appropriate measures and provide information. If you still need help, please do not hesitate to contact us.</p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Processed data types:</strong><span>&nbsp;</span>Inventory data (e.g. names, addresses), Contact data (e.g. e-mail, telephone numbers), Content data (e.g. text input, photographs, videos), Usage data (e.g. websites visited, interest in content, access times), Meta/communication data (e.g. device information, IP addresses).<br><br></li>
                <li><strong>Data subjects:</strong><span>&nbsp;</span>Users (e.g. website visitors, users of online services).<br><br></li>
               <li><strong>Purposes of Processing:</strong><span>&nbsp;</span>contact requests and communication, Targeting (e.g. profiling based on interests and behaviour, use of cookies), Remarketing, Web Analytics (e.g. access statistics, recognition of returning visitors).<br><br></li>
                <li><strong>Legal Basis:</strong><span>&nbsp;</span>Legitimate Interests (Article 6 (1) (f) GDPR).</li>
             </ul>
             <p><strong>Services and service providers being used:</strong></p>
             <ul style="font-size: 15px;" type="disc">
               <li><strong>Instagram :</strong><span>&nbsp;</span>Social network; Service provider: Instagram Inc., 1601 Willow Road, Menlo Park, CA, 94025, USA; Website:<span>&nbsp;</span><a href="https://www.instagram.com/" target="_blank" rel="noopener">https://www.instagram.com</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://instagram.com/about/legal/privacy" target="_blank" rel="noopener">https://instagram.com/about/legal/privacy</a>.<br><br></li>
               <li><strong>Facebook:</strong><span>&nbsp;</span>Social network; Service provider: Facebook Ireland Ltd., 4 Grand Canal Square, Grand Canal Harbour, Dublin 2, Irland, parent company: Facebook, 1 Hacker Way, Menlo Park, CA 94025, USA; <br>Website:<span>&nbsp;</span><a href="https://www.facebook.com/" target="_blank" rel="noopener">https://www.facebook.com</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://www.facebook.com/about/privacy" target="_blank" rel="noopener">https://www.facebook.com/about/privacy</a>; <br>Opt-Out: Settings for advertisements:<span>&nbsp;</span><a href="https://www.facebook.com/settings?tab=ads" target="_blank" rel="noopener">https://www.facebook.com/settings?tab=ads</a>;<br>Additional information on data protection: Agreement on the joint controll of processing of personal data on Facebook pages:<span>&nbsp;</span><a href="https://www.facebook.com/legal/terms/page_controller_addendum" target="_blank" rel="noopener">https://www.facebook.com/legal/terms/page_controller_addendum</a>,<br>Privacy policy for Facebook pages:<span>&nbsp;</span><a href="https://www.facebook.com/legal/terms/information_about_page_insights_data" target="_blank" rel="noopener">https://www.facebook.com/legal/terms/information_about_page_insights_data</a>.<br><br></li>
               <li><strong>LinkedIn:</strong><span>&nbsp;</span>Social network; Service provider: LinkedIn Ireland Unlimited Company, Wilton Place, Dublin 2, Ireland; Website:<span>&nbsp;</span><a href="https://www.linkedin.com/" target="_blank" rel="noopener">https://www.linkedin.com</a>; <br>Privacy Policy:<span>&nbsp;</span><a href="https://www.linkedin.com/legal/privacy-policy" target="_blank" rel="noopener">https://www.linkedin.com/legal/privacy-policy</a>; <br>Opt-Out:<span>&nbsp;</span><a href="https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out" target="_blank" rel="noopener">https://www.linkedin.com/psettings/guest-controls/retargeting-opt-out</a>.<br><br></li>
               <li><strong>Twitter:</strong><span>&nbsp;</span>Social network; Service provider: Twitter Inc., 1355 Market Street, Suite 900, San Francisco, CA 94103, USA; Privacy Policy:<span>&nbsp;</span><a href="https://twitter.com/de/privacy" target="_blank" rel="noopener">https://twitter.com/de/privacy</a>, <br>(Settings)<span>&nbsp;</span><a href="https://twitter.com/personalization" target="_blank" rel="noopener">https://twitter.com/personalization</a>.<br><br></li>
               <li><strong>YouTube:</strong><span>&nbsp;</span>Social network; Service provider: Google Ireland Limited, Gordon House, Barrow Street, Dublin 4, Ireland, parent company: Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA; Privacy Policy:<span>&nbsp;</span><a href="https://policies.google.com/privacy" target="_blank" rel="noopener">https://policies.google.com/privacy</a>; <br>Opt-Out:<span>&nbsp;</span><a href="https://adssettings.google.com/authenticated" target="_blank" rel="noopener">https://adssettings.google.com/authenticated</a>.<br><br></li>
               <li><strong>A/B Tests:</strong>&nbsp;A/B tests are designed to improve the usability and performance of online services. For example, users are presented with different versions of a website or its elements, such as input forms, on which the placement of the contents or labels of the navigation elements can differ. The behaviour of users, e.g. prolonged visits to the site or more frequent interaction with the elements, can then be used to determine which of these sites or elements are more responsive to users' needs.<br><br></li>
               <li><strong>Clicktracking:</strong>&nbsp;Clicktracking allows users to keep track of their movements within an entire website. Since the results of these tests are more accurate if the interaction of the users can be followed over a certain period of time (e.g. if a user likes to return), cookies are usually stored on the computers of the users for these test purposes.<br><br></li>
               <li><strong>Controller:</strong>&nbsp;"Controller" means the natural or legal person, public authority, agency or other body which, alone or jointly with others, determines the purposes and means of the processing of personal data.<br><br></li>
               <li><strong>Conversion Tracking:</strong>&nbsp;"Conversion Tracking" refers to a procedure by which the effectiveness of marketing measures can be determined. As a rule, a cookie is stored on the devices of the users within the websites on which the marketing measures are carried out and then called up again on the target website (e.g. this enables us to track whether the ads we placed on other websites were successful).<br><br></li>
               <li><strong>Conversion tracking:</strong>&nbsp;Conversion tracking is a method used to evaluate the effectiveness of marketing measures. For this purpose, a cookie is usually stored on the devices of the users within the websites on which the marketing measures take place and then called up again on the target website (e.g. we can thus trace whether the advertisements placed by us on other websites were successful).<br><br></li>
               <li><strong>Cross-Device Tracking:</strong>&nbsp;Cross-Device Tracking is a form of tracking in which behavior and interest information of the user is recorded across all devices in so-called profiles by assigning an online identifier to the user. This means that user information can usually be analysed for marketing purposes, regardless of the browser or device used (e.g. mobile phone or desktop computer). With most Cross-Device Tracking providers, the online identifier is not linked to plain data such as names, postal addresses or e-mail addresses.<br><br></li>
               <li><strong>Custom Audiences:&nbsp;</strong>Target group formation (or "custom audiences") is the term used when target groups are determined for advertising purposes, e.g. display of advertisements. For example, a user's interest in certain products or topics on the Internet may be used to infer that that user is interested in advertisements for similar products or the online store in which they viewed the products. Lookalike Audiences" (or similar target groups) is the term used to describe content that is viewed as suitable by users whose profiles or interests presumably correspond to the users for whom the profiles were created. Cookies are generally used for the purposes of creating custom audiences and lookalike audiences. Target groups can be created by processing visitors of an online service or can be uploaded to the provider of an online marketing technology by means of uploading (which is usually done pseudonymised).<br><br></li>
               <li><strong>Heatmaps:</strong>&nbsp;"Heatmaps" are mouse movements of the users, which are combined to an overall picture, with the help of which it can be recognized, for example, which web page elements are preferred and which web page elements users prefer less.<br><br></li>
               <li><strong>IP Masking:</strong>&nbsp;IP masking is a method by which the last octet, i.e. the last two numbers of an IP address, are deleted so that the IP address alone can no longer be used to uniquely identify a person. IP masking is therefore a means of pseudonymising processing methods, particularly in online marketing.<br><br></li>
               <li><strong>Interest-based and behavioral marketing:&nbsp;</strong>Interest-related and/or behaviour-related marketing is the term used when potential user interest in advertisements and other content is predicted if possible. This is done on the basis of information on the previous behaviour of users (e.g. visiting and staying on certain websites, purchasing behaviour or interaction with other users), which is stored in a so-called profile. For these purposes cookies are usually used.<br><br></li>
               <li><strong>Personal Data:</strong>&nbsp;"personal data" means any information relating to an identified or identifiable natural person ("data subject"); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person.<br><br></li>
               <li><strong>Processing:</strong>&nbsp;The term "processing" covers a wide range and practically every handling of data, be it collection, evaluation, storage, transmission or erasure.<br><br></li>
               <li><strong>Profiling:</strong>&nbsp;"Profiling" means any automated processing of personal data consisting in the use of such personal data to analyse, evaluate or predict certain personal aspects relating to a natural person (depending on the type of profiling, this includes information regarding age, gender, location and movement data, interaction with websites and their contents, shopping behaviour, social interactions with other people) (e.g. interests in certain contents or products, click behaviour on a website or the location). Cookies and web beacons are often used for profiling purposes.<br><br></li>
               <li><strong>Remarketing:</strong>&nbsp;Remarketing" or "retargeting" is the term used, for example, to indicate for advertising purposes which products a user is interested in on a website in order to remind the user of these products on other websites, e.g. in advertisements.&nbsp;<br><br></li>
               <li><strong>Targeting:</strong>&nbsp;Tracking" is the term used when the behaviour of users can be traced across several websites. As a rule, behavior and interest information with regard to the websites used is stored in cookies or on the servers of the tracking technology providers (so-called profiling). This information can then be used, for example, to display advertisements to users presumably corresponding to their interests.<br><br></li>
               <li><strong>Web Analytics:</strong>&nbsp;Web Analytics serves the evaluation of visitor traffic of online services and can determine their behavior or interests in certain information, such as content of websites. With the help of web analytics, website owners, for example, can recognize at what time visitors visit their website and what content they are interested in. This allows them, for example, to optimize the content of the website to better meet the needs of their visitors. For purposes of web analytics, pseudonymous cookies and web beacons are frequently used in order to recognise returning visitors and thus obtain more precise analyses of the use of an online service.</li>
             </ul>
          </span>
       </div>

   <Footer class="mt-auto"/>
</div>
</template>

