function files_written = generate_fft_eligible_cases(case_dir)
%GENERATE_FFT_ELIGIBLE_CASES Create explicit FFT-eligible and non-eligible cases.
%
% Outputs:
%   - fft_case_uniform_large.json
%   - fft_case_nonuniform_large.json

    here = fileparts(mfilename('fullpath'));
    if nargin < 1 || isempty(case_dir)
        case_dir = fullfile(here, 'fft_cases');
    end
    if ~exist(case_dir, 'dir')
        mkdir(case_dir);
    end

    files_written = cell(2, 1);

    case_uniform = make_case_uniform_large();
    case_nonuniform = make_case_nonuniform_large();

    files_written{1} = fullfile(case_dir, 'fft_case_uniform_large.json');
    files_written{2} = fullfile(case_dir, 'fft_case_nonuniform_large.json');

    write_json(case_uniform, files_written{1});
    write_json(case_nonuniform, files_written{2});
end

function c = make_case_uniform_large()
    c = struct();
    c.meta = struct( ...
        'case_id', 'fft_case_uniform_large', ...
        'source_solver', 'internal_fft_validation', ...
        'description', 'Uniform-lattice winding layout intended to be FFT-eligible');

    c.inputs = struct();
    c.inputs.designRequirements = struct( ...
        'topology', 'fft_validation', ...
        'magnetizingInductance', struct('nominal', 120e-6), ...
        'turnsRatios', {{struct('nominal', 1.0)}} ...
    );
    c.inputs.operatingPoints = struct('name', 'nominal', 'frequency_hz', 150e3, 'conditions', struct('ambientTemperature', 25));

    windings = struct([]);
    windings(1) = struct( ...
        'name', 'Primary', ...
        'turns', 400, ...      % 20x20 lattice from execute_mas_case turn placement
        'n_filar', 1, ...
        'current_a', 4.5, ...
        'phase_deg', 0, ...
        'wire', struct('shape', 'round', 'kind', 'round', 'width_m', 0.40e-3, 'height_m', 0.40e-3, 'diameter_m', 0.40e-3) ...
    );

    c.benchmark = build_benchmark_block(150e3, 2, 2, windings, struct('layer_m', 0.12e-3, 'filar_m', 0.08e-3, 'winding_m', 0.12e-3));
end

function c = make_case_nonuniform_large()
    c = struct();
    c.meta = struct( ...
        'case_id', 'fft_case_nonuniform_large', ...
        'source_solver', 'internal_fft_validation', ...
        'description', 'Mixed-wire, mixed-spacing layout intended to fail FFT eligibility');

    c.inputs = struct();
    c.inputs.designRequirements = struct( ...
        'topology', 'fft_validation', ...
        'magnetizingInductance', struct('nominal', 120e-6), ...
        'turnsRatios', {{struct('nominal', 1.5)}} ...
    );
    c.inputs.operatingPoints = struct('name', 'nominal', 'frequency_hz', 150e3, 'conditions', struct('ambientTemperature', 25));

    windings = struct([]);
    windings(1) = struct( ...
        'name', 'Primary', ...
        'turns', 196, ...
        'n_filar', 1, ...
        'current_a', 4.5, ...
        'phase_deg', 0, ...
        'wire', struct('shape', 'round', 'kind', 'round', 'width_m', 0.45e-3, 'height_m', 0.45e-3, 'diameter_m', 0.45e-3) ...
    );
    windings(2) = struct( ...
        'name', 'Secondary', ...
        'turns', 180, ...
        'n_filar', 2, ...
        'current_a', 7.0, ...
        'phase_deg', 180, ...
        'wire', struct('shape', 'rectangular', 'kind', 'rectangular', 'width_m', 0.70e-3, 'height_m', 0.25e-3) ...
    );

    c.benchmark = build_benchmark_block(150e3, 2, 2, windings, struct('layer_m', 0.10e-3, 'filar_m', 0.06e-3, 'winding_m', 0.40e-3));
end

function b = build_benchmark_block(freq_hz, Nx, Ny, windings, gaps)
    b = struct();
    b.frequency_hz = freq_hz;
    b.sigma_s_per_m = 5.8e7;
    b.mu0_h_per_m = 4 * pi * 1e-7;
    b.mesh = struct('Nx', Nx, 'Ny', Ny);
    b.core = struct( ...
        'Ae', 52e-6, ...
        'le', 62e-3, ...
        'Ve', 3.2e-6, ...
        'MLT', 80e-3, ...
        'mu_r', 2200, ...
        'bobbin_w', 12e-3, ...
        'bobbin_h', 8e-3, ...
        'gap_total_m', 120e-6);
    b.geometry = struct();
    b.geometry.windings = windings;
    b.geometry.gaps = gaps;
end

function write_json(payload, out_file)
    fid = fopen(out_file, 'w');
    if fid == -1
        error('generate_fft_eligible_cases: cannot write %s', out_file);
    end
    fwrite(fid, jsonencode(payload));
    fclose(fid);
end
