function opts = solver_option_profile(mode)
%SOLVER_OPTION_PROFILE Return standardized solver option presets.

    if nargin < 1 || isempty(mode)
        mode = 'standard';
    end
    mode = lower(strtrim(char(mode)));

    opts = struct();
    opts.mode = mode;
    opts.target_rel_error_loss = 0.025;
    opts.target_rel_error_llk = 0.025;
    opts.runtime_cap_s = 8.0;
    opts.max_refine_iters = 5;
    opts.cap_behavior = 'best_so_far_warn';
    opts.enable_adaptive_meshing = true;
    opts.refine_step = 1;
    opts.max_mesh_Nx = 16;
    opts.max_mesh_Ny = 16;
    opts.enable_surface_impedance_auto = true;
    opts.surface_impedance_min_ratio = 0.75;
    opts.surface_impedance_factor_cap = 25.0;
    opts.enable_exact_rect_kernel = true;
    opts.near_singular_floor_m = 1e-12;
    opts.enable_end_turn_correction = true;
    opts.end_turn_base_factor = 0.06;
    opts.enable_litz_homogenized_now = false;
    opts.enable_geometry_cache = true;
    opts.geometry_cache_entries = 3;
    opts.enable_solver_cache = true;
    opts.solver_cache_entries = 8;
    opts.linear_solver = 'auto';                % 'auto' | 'direct' | 'gmres' | 'bicgstab'
    opts.matrix_mode = 'auto';                  % 'auto' | 'dense' | 'matrix_free'
    opts.interaction_backend = 'auto';          % 'auto' | 'dense' | 'fft' | 'fmm'
    opts.fft_auto_min_nf = 800;                 % don't auto-pick FFT for very small systems
    opts.fft_auto_min_estimated_speedup = 1.10; % estimated dense/fft matvec speedup gate
    opts.fft_auto_max_pad_ratio = 20.0;         % reject FFT when padding overhead is excessive
    opts.fmm_provider = 'auto';                 % 'auto' or external provider function name
    opts.fmm_auto_min_nf = 2500;                % only auto-pick FMM on larger irregular systems
    opts.iter_min_size_for_use = 1e10;          % disabled: keep iterative solver opt-in only (dense systems typically slower with BiCGSTAB)
    opts.fast_direct_guard_nf_max = 1e10;       % fast mode: direct-only (dense matvec overhead exceeds solver savings)
    opts.standard_direct_guard_nf_max = 1e10;   % standard mode: direct-only until sparse/FFT backends available
    opts.iter_auto_solver = 'bicgstab';         % solver used when linear_solver='auto'
    opts.iter_tol = 5e-7;
    opts.iter_maxit = 80;
    opts.iter_restart = 30;
    opts.iter_backend = 'auto';                 % 'auto' | 'octave' | 'external'
    opts.iter_external_solver_name = '';        % function name for external Krylov backend
    opts.iter_external_solver_fn = [];          % function_handle for external Krylov backend
    opts.enable_external_krylov = false;        % rollout gate: keep external backend disabled by default
    opts.external_backend_min_nf = 1800;        % don't use external backend on small systems
    opts.external_backend_allow_matrix_free = false; % first delivery: dense A only by default
    opts.iter_accept_relres_max_fast = 1e-2;
    opts.iter_accept_relres_max_standard = 5e-4;
    opts.preconditioner = 'jacobi';             % 'none' | 'jacobi' | 'ilu_sparse_drop'
    opts.precond_drop_tol = 5e-3;
    opts.enable_iter_precond_cache = true;
    opts.iter_precond_cache_entries = 6;
    opts.enable_iterative_retry = true;
    opts.iterative_retry_max = 2;
    opts.iterative_retry_relax_tol = 4.0;
    opts.iterative_retry_maxit_scale = 1.8;
    opts.iter_quality_guard_loss_jump_pct = 120.0;
    opts.enable_adaptive_harmonic_truncation = true;
    opts.harmonic_min_keep = 1;
    opts.enable_op_early_stop = true;
    opts.op_early_stop_window = 3;
    opts.op_early_stop_tol_pct = 0.25;
    opts.op_early_stop_min_points = 4;
    opts.refine_stagnation_window = 2;
    opts.refine_stagnation_tol = 0.05;
    opts.adaptive_step_auto = true;
    opts.adaptive_step_max = 3;
    opts.adaptive_step_gain = 0.85;
    opts.adaptive_step_relax = 0.45;
    opts.enable_mor = false;
    opts.mor_method = 'none';                   % 'none' | 'pod'
    opts.mor_rank = 0;
    opts.mor_energy_threshold = 0.999;
    opts.mor_training_freqs_hz = [];
    opts.lock_standard_targets = true;

    switch mode
        case 'fast'
            opts.target_rel_error_loss = 0.05;
            opts.target_rel_error_llk = 0.05;
            opts.runtime_cap_s = 4.0;
            opts.max_refine_iters = 2;
            opts.max_mesh_Nx = 10;
            opts.max_mesh_Ny = 10;
            opts.enable_exact_rect_kernel = false;
            opts.enable_end_turn_correction = false;
            opts.geometry_cache_entries = 4;
            opts.solver_cache_entries = 10;
            opts.linear_solver = 'auto';
            opts.iter_min_size_for_use = opts.fast_direct_guard_nf_max;
            opts.iter_tol = 1e-2;
            opts.iter_maxit = 220;
            opts.iter_restart = 40;
            opts.matrix_mode = 'auto';
            opts.interaction_backend = 'auto';
            opts.preconditioner = 'ilu_sparse_drop';
            opts.precond_drop_tol = 5e-3;
            opts.op_early_stop_window = 2;
            opts.op_early_stop_tol_pct = 0.35;
            opts.op_early_stop_min_points = 3;
            opts.enable_mor = true;
            opts.mor_method = 'pod';
            opts.mor_rank = 8;
            opts.iter_backend = 'auto';
            opts.enable_external_krylov = false;
        case 'high'
            opts.target_rel_error_loss = 0.01;
            opts.target_rel_error_llk = 0.01;
            opts.runtime_cap_s = 20.0;
            opts.max_refine_iters = 8;
            opts.max_mesh_Nx = 24;
            opts.max_mesh_Ny = 24;
            opts.geometry_cache_entries = 6;
            opts.solver_cache_entries = 16;
            opts.linear_solver = 'direct';      % keep reference mode deterministic/high-accuracy
            opts.matrix_mode = 'dense';
            opts.interaction_backend = 'dense';
            opts.iter_backend = 'octave';
            opts.enable_external_krylov = false;
            opts.iter_tol = 1e-8;
            opts.iter_maxit = 120;
            opts.preconditioner = 'ilu_sparse_drop';
            opts.precond_drop_tol = 1e-3;
            opts.op_early_stop_window = 5;
            opts.op_early_stop_tol_pct = 0.10;
            opts.op_early_stop_min_points = 6;
        case {'compatibility', 'legacy'}
            opts.mode = 'compatibility';
            opts.target_rel_error_loss = 0.08;
            opts.target_rel_error_llk = 0.08;
            opts.runtime_cap_s = 8.0;
            opts.max_refine_iters = 1;
            opts.enable_adaptive_meshing = false;
            opts.enable_surface_impedance_auto = false;
            opts.enable_exact_rect_kernel = false;
            opts.enable_end_turn_correction = false;
            opts.cap_behavior = 'best_so_far_warn';
            opts.enable_geometry_cache = true;
            opts.enable_solver_cache = true;
            opts.linear_solver = 'direct';
            opts.matrix_mode = 'dense';
            opts.interaction_backend = 'dense';
            opts.enable_adaptive_harmonic_truncation = false;
            opts.enable_op_early_stop = false;
            opts.adaptive_step_auto = false;
            opts.lock_standard_targets = false;
        otherwise
            opts.mode = 'standard';
    end
end
