function topology_defs = topology_metadata()
% TOPOLOGY_METADATA Returns complete topology and field metadata registry
%
% Usage:
%   topology_defs = topology_metadata();
%
% Output:
%   topology_defs - struct containing TOPOLOGY_DEFINITIONS and FIELD_METADATA
%
% This function serves as the centralized registry for all 9 converter topologies
% and their associated field requirements, constraints, and display properties.

% ==============================================================================
% TOPOLOGY DEFINITIONS
% ==============================================================================

TOPOLOGY_DEFINITIONS = struct();

% Two-Switch Forward
TOPOLOGY_DEFINITIONS.two_switch_forward = struct(...
    'display_name', 'Two-Switch Forward', ...
    'mas_filename', 'forward.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop', 'currentRippleRatio'}}, ...
    'optional_fields', {{'inputVoltage_nominal', 'efficiency', 'maximumSwitchCurrent', 'maximumDutyCycle'}} ...
);

% Single-Switch Forward (same schema as Two-Switch Forward but with demagnetization winding)
TOPOLOGY_DEFINITIONS.single_switch_forward = struct(...
    'display_name', 'Single-Switch Forward', ...
    'mas_filename', 'forward.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop', 'currentRippleRatio'}}, ...
    'optional_fields', {{'inputVoltage_nominal', 'efficiency', 'maximumSwitchCurrent', 'maximumDutyCycle'}} ...
);

% Active Clamp Forward (same as Two-Switch Forward)
TOPOLOGY_DEFINITIONS.active_clamp_forward = struct(...
    'display_name', 'Active Clamp Forward', ...
    'mas_filename', 'forward.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop', 'currentRippleRatio'}}, ...
    'optional_fields', {{'inputVoltage_nominal', 'efficiency', 'maximumSwitchCurrent', 'maximumDutyCycle'}} ...
);

% Flyback
TOPOLOGY_DEFINITIONS.flyback = struct(...
    'display_name', 'Flyback', ...
    'mas_filename', 'flyback.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop', 'currentRippleRatio', 'efficiency'}}, ...
    'optional_fields', {{'inputVoltage_nominal', 'maximumDutyCycle', 'maximumDrainSourceVoltage', 'maximumSwitchCurrent'}} ...
);

% Push-Pull
TOPOLOGY_DEFINITIONS.push_pull = struct(...
    'display_name', 'Push-Pull', ...
    'mas_filename', 'pushPull.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop', 'currentRippleRatio'}}, ...
    'optional_fields', {{'inputVoltage_nominal', 'efficiency', 'dutyCycle', 'maximumSwitchCurrent', 'maximumDrainSourceVoltage'}} ...
);

% Buck
TOPOLOGY_DEFINITIONS.buck = struct(...
    'display_name', 'Buck', ...
    'mas_filename', 'buck.json', ...
    'output_type', 'single', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltage', 'outputCurrent', ...
                         'switchingFrequency', 'diodeVoltageDrop'}}, ...
    'optional_fields', {{'currentRippleRatio', 'maximumSwitchCurrent', 'efficiency', 'inputVoltage_nominal'}} ...
);

% Boost
TOPOLOGY_DEFINITIONS.boost = struct(...
    'display_name', 'Boost', ...
    'mas_filename', 'boost.json', ...
    'output_type', 'single', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltage', 'outputCurrent', ...
                         'switchingFrequency', 'diodeVoltageDrop'}}, ...
    'optional_fields', {{'currentRippleRatio', 'maximumSwitchCurrent', 'efficiency', 'inputVoltage_nominal'}} ...
);

% Isolated Buck
TOPOLOGY_DEFINITIONS.isolated_buck = struct(...
    'display_name', 'Isolated Buck', ...
    'mas_filename', 'isolatedBuck.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop'}}, ...
    'optional_fields', {{'currentRippleRatio', 'maximumSwitchCurrent', 'efficiency', 'inputVoltage_nominal'}} ...
);

% Isolated Buck-Boost
TOPOLOGY_DEFINITIONS.isolated_buck_boost = struct(...
    'display_name', 'Isolated Buck-Boost', ...
    'mas_filename', 'isolatedBuckBoost.json', ...
    'output_type', 'multi', ...
    'required_fields', {{'inputVoltage_minimum', 'inputVoltage_maximum', ...
                         'outputVoltages_0', 'outputCurrents_0', ...
                         'switchingFrequency', 'diodeVoltageDrop'}}, ...
    'optional_fields', {{'currentRippleRatio', 'maximumSwitchCurrent', 'efficiency', 'inputVoltage_nominal'}} ...
);

% ==============================================================================
% FIELD METADATA
% ==============================================================================

FIELD_METADATA = struct();

% Input Voltage Fields
FIELD_METADATA.inputVoltage_minimum = struct(...
    'label', 'Input Voltage Min', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 100, ...
    'min', 5, ...
    'max', 1000, ...
    'tooltip', 'Minimum input voltage', ...
    'mas_path', 'inputs.designRequirements.inputVoltage.minimum', ...
    'optional', false ...
);

FIELD_METADATA.inputVoltage_maximum = struct(...
    'label', 'Input Voltage Max', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 190, ...
    'min', 5, ...
    'max', 1000, ...
    'tooltip', 'Maximum input voltage', ...
    'mas_path', 'inputs.designRequirements.inputVoltage.maximum', ...
    'optional', false ...
);

FIELD_METADATA.inputVoltage_nominal = struct(...
    'label', 'Input Voltage Nom.', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', [], ...
    'min', 5, ...
    'max', 1000, ...
    'tooltip', 'Nominal input voltage (optional)', ...
    'mas_path', 'inputs.designRequirements.inputVoltage.nominal', ...
    'optional', true ...
);

% Output Voltage/Current Fields (multi-output, indexed _0, _1, _2, _3)
FIELD_METADATA.outputVoltages_0 = struct(...
    'label', 'Output 1 Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Primary/first output voltage', ...
    'mas_path', 'inputs.operatingPoints(1).outputVoltages(1)', ...
    'optional', false ...
);

FIELD_METADATA.outputVoltages_1 = struct(...
    'label', 'Output 2 Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Second output voltage', ...
    'mas_path', 'inputs.operatingPoints(1).outputVoltages(2)', ...
    'optional', true ...
);

FIELD_METADATA.outputVoltages_2 = struct(...
    'label', 'Output 3 Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Third output voltage', ...
    'mas_path', 'inputs.operatingPoints(1).outputVoltages(3)', ...
    'optional', true ...
);

FIELD_METADATA.outputVoltages_3 = struct(...
    'label', 'Output 4 Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Fourth output voltage', ...
    'mas_path', 'inputs.operatingPoints(1).outputVoltages(4)', ...
    'optional', true ...
);

FIELD_METADATA.outputCurrents_0 = struct(...
    'label', 'Output 1 Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Primary/first output current', ...
    'mas_path', 'inputs.operatingPoints(1).outputCurrents(1)', ...
    'optional', false ...
);

FIELD_METADATA.outputCurrents_1 = struct(...
    'label', 'Output 2 Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Second output current', ...
    'mas_path', 'inputs.operatingPoints(1).outputCurrents(2)', ...
    'optional', true ...
);

FIELD_METADATA.outputCurrents_2 = struct(...
    'label', 'Output 3 Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Third output current', ...
    'mas_path', 'inputs.operatingPoints(1).outputCurrents(3)', ...
    'optional', true ...
);

FIELD_METADATA.outputCurrents_3 = struct(...
    'label', 'Output 4 Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Fourth output current', ...
    'mas_path', 'inputs.operatingPoints(1).outputCurrents(4)', ...
    'optional', true ...
);

% Single Output Fields (for Buck/Boost)
FIELD_METADATA.outputVoltage = struct(...
    'label', 'Output Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Single output voltage', ...
    'mas_path', 'inputs.designRequirements.outputVoltage', ...
    'optional', false ...
);

FIELD_METADATA.outputCurrent = struct(...
    'label', 'Output Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', 5, ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Single output current', ...
    'mas_path', 'inputs.designRequirements.outputCurrent', ...
    'optional', false ...
);

% Control Parameters
FIELD_METADATA.switchingFrequency = struct(...
    'label', 'Switching Frequency', ...
    'unit', 'kHz', ...
    'data_type', 'number', ...
    'default', 200, ...
    'min', 10, ...
    'max', 10000, ...
    'tooltip', 'Switching frequency of converter', ...
    'mas_path', 'inputs.operatingPoints(1).switchingFrequency', ...
    'optional', false ...
);

FIELD_METADATA.diodeVoltageDrop = struct(...
    'label', 'Diode Voltage Drop', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', 0.7, ...
    'min', 0.3, ...
    'max', 1.5, ...
    'tooltip', 'Forward voltage drop of output diode', ...
    'mas_path', 'inputs.designRequirements.diodeVoltageDrop', ...
    'optional', false ...
);

FIELD_METADATA.currentRippleRatio = struct(...
    'label', 'Current Ripple %', ...
    'unit', '%', ...
    'data_type', 'number', ...
    'default', 30, ...
    'min', 5, ...
    'max', 100, ...
    'tooltip', 'Output current ripple as percentage of average current', ...
    'mas_path', 'inputs.designRequirements.currentRippleRatio', ...
    'optional', false ...
);

FIELD_METADATA.efficiency = struct(...
    'label', 'Efficiency', ...
    'unit', '%', ...
    'data_type', 'number', ...
    'default', 90, ...
    'min', 50, ...
    'max', 99, ...
    'tooltip', 'Expected converter efficiency (not used in advisor, informational)', ...
    'mas_path', 'inputs.designRequirements.efficiency', ...
    'optional', true ...
);

FIELD_METADATA.maximumSwitchCurrent = struct(...
    'label', 'Max Switch Current', ...
    'unit', 'A', ...
    'data_type', 'number', ...
    'default', [], ...
    'min', 0.1, ...
    'max', 1000, ...
    'tooltip', 'Maximum switch current (optional constraint)', ...
    'mas_path', 'inputs.designRequirements.maximumSwitchCurrent', ...
    'optional', true ...
);

FIELD_METADATA.maximumDutyCycle = struct(...
    'label', 'Max Duty Cycle', ...
    'unit', '%', ...
    'data_type', 'number', ...
    'default', [], ...
    'min', 1, ...
    'max', 99, ...
    'tooltip', 'Maximum duty cycle constraint', ...
    'mas_path', 'inputs.designRequirements.maximumDutyCycle', ...
    'optional', true ...
);

FIELD_METADATA.dutyCycle = struct(...
    'label', 'Duty Cycle', ...
    'unit', '%', ...
    'data_type', 'number', ...
    'default', [], ...
    'min', 1, ...
    'max', 99, ...
    'tooltip', 'Nominal duty cycle for topology', ...
    'mas_path', 'inputs.designRequirements.dutyCycle', ...
    'optional', true ...
);

FIELD_METADATA.maximumDrainSourceVoltage = struct(...
    'label', 'Max Drain-Source Voltage', ...
    'unit', 'V', ...
    'data_type', 'number', ...
    'default', [], ...
    'min', 1, ...
    'max', 10000, ...
    'tooltip', 'Maximum drain-source voltage (MOSFET rating constraint)', ...
    'mas_path', 'inputs.designRequirements.maximumDrainSourceVoltage', ...
    'optional', true ...
);

% ==============================================================================
% BUILD OUTPUT STRUCTURE
% ==============================================================================

topology_defs.TOPOLOGY_DEFINITIONS = TOPOLOGY_DEFINITIONS;
topology_defs.FIELD_METADATA = FIELD_METADATA;

end
